@echo off
echo Removing old devices...
"C:\Users\User\Desktop\driver\devcon.exe" remove Root\AirTuneAudio
echo Deleting old driver package...
pnputil /delete-driver oem4.inf /force
echo Installing new driver...
pnputil /add-driver "C:\Users\User\Desktop\driver\AirTuneAudio.inf" /install
echo Creating device...
"C:\Users\User\Desktop\driver\devcon.exe" install "C:\Users\User\Desktop\driver\AirTuneAudio.inf" Root\AirTuneAudio
echo Done!
pause
